language: python
python:
    - "3.4"
cache:
  directories:
    - $HOME/.pip-cache/
install:
    - pip install -r requirements.txt --download-cache $HOME/.pip-cache --use-mirrors
    - pip install -r requirements-dev.txt --download-cache $HOME/.pip-cache --use-mirrors
script:
    - cd peacecorps
    - python manage.py test --settings=peacecorps.settings.test
